<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Export Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            font-size: 12px;

        }

        .header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid #3498db;
        }
        .header h1 {
            color: #2c3e50;
            margin-bottom: 5px;
            font-size: 28px;
        }
        .header p {
            color: #7f8c8d;
            font-size: 16px;
        }
        .metadata {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
            font-size: 14px;
            color: #555;
            background-color: #f8f9fa;
            padding: 12px 15px;
            border-radius: 5px;
        }
        table {
        width: 100%;
        border-collapse: collapse;
        font-size: 10px; /* Réduire la taille du texte */
    }
    th, td {
        padding: 6px 8px;
        border: 1px solid #ddd;
        text-align: left;
        word-break: break-word;
    }
    th {
        background-color: #3498db;
        color: white;
        font-weight: bold;
        text-transform: uppercase;
    }
    td {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #7f8c8d;
            padding-top: 15px;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>User Management Report</h1>
        <p>Complete list of registered users</p>
    </div>

    <div class="metadata">
        <div>
            <strong>Export Date:</strong> {{ now()->format('F j, Y \a\t H:i') }}
        </div>
        <div>
            <strong>Total Users:</strong> {{ $users->count() }}
        </div>
        <div>
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Email Address</th>
                <th>Address</th>
                <th>Postal Code</th>
                <th>Phone Number</th>
                <th>Registration Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr>
                <td>#{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->address ?? 'N/A' }}</td>
                <td>{{ $user->postal_code ?? 'N/A' }}</td>
                <td>{{ $user->phone_number ?? 'N/A' }}</td>
                <td>
                    @if($user->created_at)
                        {{ \Carbon\Carbon::parse($user->created_at)->format('M j, Y') }}
                    @else
                        N/A
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Confidential document - Generated by {{ config('app.name') }} &copy; {{ date('Y') }}</p>
        <p>Page <span class="pageNumber"></span> - Printed on {{ now()->format('F j, Y') }}</p>
    </div>

    <script>
        // Page numbering for PDF
        document.addEventListener('DOMContentLoaded', function() {
            const pages = document.querySelectorAll('.pageNumber');
            pages.forEach((page, index) => {
                page.textContent = (index + 1);
            });
        });
    </script>

</body>
</html>
