<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Export Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid #3498db;
        }
        .header h1 {
            color: #2c3e50;
            margin-bottom: 5px;
            font-size: 28px;
        }
        .header p {
            color: #7f8c8d;
            font-size: 16px;
        }
        .metadata {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
            font-size: 14px;
            color: #555;
            background-color: #f8f9fa;
            padding: 12px 15px;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        th {
            background-color: #3498db;
            color: white;
            text-align: left;
            padding: 12px 15px;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 13px;
        }
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #e0e0e0;
            vertical-align: top;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #7f8c8d;
            padding-top: 15px;
            border-top: 1px solid #eee;
        }
        .badge {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .badge-admin {
            background-color: #9b59b6;
            color: white;
        }
        .badge-user {
            background-color: #3498db;
            color: white;
        }
        .logo {
            text-align: center;
            margin-bottom: 20px;
        }
        .logo img {
            max-height: 60px;
        }
    </style>
</head>
<body>


    <div class="header">
        <h1>User Management Report</h1>
        <p>Complete list of registered users</p>
    </div>

    <div class="metadata">
        <div>
            <strong>Export Date:</strong> {{ now()->format('F j, Y \a\t H:i') }}
        </div>
        <div>
            <strong>Total Users:</strong> {{ $users->count() }}
        </div>
        <div>
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Email Address</th>
                <th>Registration Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr>
                <td>#{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>

                <td>
                    @if($user->created_at)
                        {{ \Carbon\Carbon::parse($user->created_at)->format('M j, Y') }}
                    @else
                        N/A
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Confidential document - Generated by {{ config('app.name') }} &copy; {{ date('Y') }}</p>
        <p>Page <span class="pageNumber"></span> - Printed on {{ now()->format('F j, Y') }}</p>
    </div>

    <script>
        // Page numbering for PDF
        document.addEventListener('DOMContentLoaded', function() {
            const pages = document.querySelectorAll('.pageNumber');
            pages.forEach((page, index) => {
                page.textContent = (index + 1);
            });
        });
    </script>
</body>
</html>
