<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products Export Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid #2ecc71;
        }
        .header h1 {
            color: #27ae60;
            margin-bottom: 5px;
            font-size: 28px;
        }
        .header p {
            color: #7f8c8d;
            font-size: 16px;
        }
        .metadata {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
            font-size: 14px;
            color: #555;
            background-color: #f8f9fa;
            padding: 12px 15px;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        th {
            background-color: #2ecc71;
            color: white;
            text-align: left;
            padding: 12px 15px;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 13px;
        }
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #e0e0e0;
            vertical-align: top;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #7f8c8d;
            padding-top: 15px;
            border-top: 1px solid #eee;
        }
        .badge {
            display: inline-block;
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .badge-instock {
            background-color: #2ecc71;
            color: white;
        }
        .badge-outstock {
            background-color: #e74c3c;
            color: white;
        }
        .logo {
            text-align: center;
            margin-bottom: 20px;
        }
        .logo img {
            max-height: 60px;
        }
        .price {
            font-weight: bold;
            color: #27ae60;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Product Inventory Report</h1>
        <p>Complete list of available products</p>
    </div>

    <div class="metadata">
        <div>
            <strong>Export Date:</strong> {{ now()->format('F j, Y \a\t H:i') }}
        </div>
        <div>
            <strong>Total Products:</strong> {{ $products->count() }}
        </div>
        <div>
            <strong>Total Value:</strong> ${{ number_format($products->sum('price'), 2) }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Product Name</th>
                <th>Category</th>
                <th class="text-right">Price</th>
                <th class="text-center">Stock</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
            <tr>
                <td>#{{ $product->id }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category }}</td>
                <td class="text-right price">${{ number_format($product->price, 2) }}</td>
                <td class="text-center">{{ $product->stock }}</td>
                <td>
                    @if($product->stock > 0)
                        <span class="badge badge-instock">In Stock</span>
                    @else
                        <span class="badge badge-outstock">Out of Stock</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Confidential document - Generated by {{ config('app.name') }} &copy; {{ date('Y') }}</p>
        <p>Page <span class="pageNumber"></span> - Printed on {{ now()->format('F j, Y') }}</p>
    </div>

    <script>
        // Page numbering for PDF
        document.addEventListener('DOMContentLoaded', function() {
            const pages = document.querySelectorAll('.pageNumber');
            pages.forEach((page, index) => {
                page.textContent = (index + 1);
            });
        });
    </script>
</body>
</html>
