<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products Export Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid #3498db;
        }
        .header h1 {
            color: #2c3e50;
            margin-bottom: 5px;
            font-size: 28px;
        }
        .header p {
            color: #7f8c8d;
            font-size: 16px;
        }
        .metadata {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
            font-size: 14px;
            color: #555;
            background-color: #f8f9fa;
            padding: 12px 15px;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
            margin-bottom: 15px;
        }
        th, td {
            padding: 6px 8px;
            border: 1px solid #ddd;
            text-align: left;
        }
        th {
            background-color: #3498db;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #7f8c8d;
            padding-top: 15px;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Products Export Report</h1>
        <p>Complete list of products in the system</p>
    </div>

    <div class="metadata">
        <div>
            <strong>Export Date:</strong> {{ now()->format('F j, Y \a\t H:i') }}
        </div>
        <div>
            <strong>Total Products:</strong> {{ $products->count() }}
        </div>
        <div>
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Category</th>
                <th>Stock</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
            <tr>
                <td>#{{ $product->id }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ Str::limit($product->description, 50) }}</td>
                <td>{{ number_format($product->price, 2) }} DT</td>
                <td>{{ $product->category }}</td>
                <td>{{ $product->stock }}</td>
                <td>{{ $product->stock > 0 ? 'In Stock' : 'Out of Stock' }}</td>
                <td>{{ $product->created_at->format('M j, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Confidential document - Generated by {{ config('app.name') }} &copy; {{ date('Y') }}</p>
        <p>Page <span class="pageNumber"></span> - Printed on {{ now()->format('F j, Y') }}</p>
    </div>

    <script>
        // Page numbering for PDF
        document.addEventListener('DOMContentLoaded', function() {
            const pages = document.querySelectorAll('.pageNumber');
            pages.forEach((page, index) => {
                page.textContent = (index + 1);
            });
        });
    </script>

</body>
</html>
