<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users with Products Export Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid #3498db;
        }
        .header h1 {
            color: #2c3e50;
            margin-bottom: 5px;
            font-size: 28px;
        }
        .header p {
            color: #7f8c8d;
            font-size: 16px;
        }
        .metadata {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
            font-size: 14px;
            color: #555;
            background-color: #f8f9fa;
            padding: 12px 15px;
            border-radius: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
            margin-bottom: 15px;
        }
        th, td {
            padding: 6px 8px;
            border: 1px solid #ddd;
            text-align: left;
        }
        th {
            background-color: #3498db;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
        }
        .user-row {
            background-color: #f8f9fa;
        }
        .product-row td {
            padding-left: 25px;
            background-color: #fff;
        }
        .product-header {
            background-color: #e9ecef;
            font-weight: bold;
        }
        .no-products {
            color: #6c757d;
            font-style: italic;
            text-align: center;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #7f8c8d;
            padding-top: 15px;
            border-top: 1px solid #eee;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Users with Products Report</h1>
        <p>Complete list of users and their associated products</p>
    </div>

    <div class="metadata">
        <div>
            <strong>Export Date:</strong> {{ now()->format('F j, Y \a\t H:i') }}
        </div>
        <div>
            <strong>Total Users:</strong> {{ $users->count() }}
        </div>
        <div>
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th colspan="7" class="product-header">User Information</th>
            </tr>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Postal Code</th>
                <th>Phone</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
            <tr class="user-row">
                <td>#{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->adresse ?? 'N/A' }}</td>
                <td>{{ $user->code_postal ?? 'N/A' }}</td>
                <td>{{ $user->numero ?? 'N/A' }}</td>
                <td>{{ $user->created_at->format('M j, Y') }}</td>
            </tr>

            <!-- Products Section -->
            <tr>
                <td colspan="7" class="product-header">Associated Products</td>
            </tr>

            @if($user->products && $user->products->count() > 0)
                <tr>
                    <th>Product ID</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Category</th>
                    <th>Stock</th>
                    <th>Status</th>
                    <th>Added On</th>
                </tr>

                @foreach($user->products as $product)
                <tr class="product-row">
                    <td>#{{ $product->id }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ number_format($product->price, 2) }} DT</td>
                    <td>{{ $product->category }}</td>
                    <td>{{ $product->stock }}</td>
                    <td>{{ $product->stock > 0 ? 'In Stock' : 'Out of Stock' }}</td>
                    <td>{{ $product->created_at->format('M j, Y') }}</td>
                </tr>
                @endforeach
            @else
                <tr class="product-row">
                    <td colspan="7" class="no-products">No products associated with this user</td>
                </tr>
            @endif

            <!-- Spacer between users -->
            <tr>
                <td colspan="7" style="border: none; height: 15px;"></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Confidential document - Generated by {{ config('app.name') }} &copy; {{ date('Y') }}</p>
        <p>Page <span class="pageNumber"></span> - Printed on {{ now()->format('F j, Y') }}</p>
    </div>

    <script>
        // Page numbering for PDF
        document.addEventListener('DOMContentLoaded', function() {
            const pages = document.querySelectorAll('.pageNumber');
            pages.forEach((page, index) => {
                page.textContent = (index + 1);
            });
        });
    </script>

</body>
</html>
